name: Veronica
main: me.snakesdevelopment.veronica.Main
version: 1.0
api-version: 1.12
author: SnakesDevelopment
commands:
   level:
      usage: /<command>
   rewards:
      usage: /<command>
